#!/bin/sh


this_dir=$(cd $(dirname $0) && pwd)

if [ ! -f $this_dir/unit-tests/.test-agent-pid ]; then
MIBDIRS=+$this_dir/unit-tests snmpd -r -C -p $this_dir/unit-tests/.test-agent-pid -Isystem_mib -c $this_dir/unit-tests/guileSnmpTestMIB-emulation.conf  
sleep 1
fi

$this_dir/dev-environ "$@"

# could kill agent here, but when!

