/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef GSTTABBTABLE_OIDS_H
#define GSTTABBTABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table gstTabBTable 
     */
#define GSTTABBTABLE_OID              1,3,6,1,3,1977,1,4

#define COLUMN_GSTTABBINDEX         1

#define COLUMN_GSTTABBINDEX2         2

#define COLUMN_GSTTABBDATA         3


#define GSTTABBTABLE_MIN_COL   COLUMN_GSTTABBINDEX
#define GSTTABBTABLE_MAX_COL   COLUMN_GSTTABBDATA



#ifdef __cplusplus
}
#endif
#endif                          /* GSTTABBTABLE_OIDS_H */
