/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/** \page MFD helper for gstTabBTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/*
 * standard Net-SNMP includes 
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/*
 * include our parent header 
 */
#include "gstTabBTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "gstTabBTable_interface.h"

oid             gstTabBTable_oid[] = { GSTTABBTABLE_OID };

int             gstTabBTable_oid_size = OID_LENGTH(gstTabBTable_oid);

gstTabBTable_registration gstTabBTable_user_context;

void            initialize_table_gstTabBTable(void);
void            shutdown_table_gstTabBTable(void);


/**
 * Initializes the gstTabBTable module
 */
void
init_gstTabBTable(void)
{
    DEBUGMSGTL(("verbose:gstTabBTable:init_gstTabBTable", "called\n"));

    /*
     * TODO:300:o: Perform gstTabBTable one-time module initialization.
     */

    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("gstTabBTable"))
        initialize_table_gstTabBTable();

}                               /* init_gstTabBTable */

/**
 * Shut-down the gstTabBTable module (agent is exiting)
 */
void
shutdown_gstTabBTable(void)
{
    if (should_init("gstTabBTable"))
        shutdown_table_gstTabBTable();

}

/**
 * Initialize the table gstTabBTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_gstTabBTable(void)
{
    gstTabBTable_registration *user_context;
    u_long          flags;

    DEBUGMSGTL(("verbose:gstTabBTable:initialize_table_gstTabBTable",
                "called\n"));

    /*
     * TODO:301:o: Perform gstTabBTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize gstTabBTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("gstTabBTable", NULL, NULL);

    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;

    /*
     * call interface initialization code
     */
    _gstTabBTable_initialize_interface(user_context, flags);
}                               /* initialize_table_gstTabBTable */

/**
 * Shutdown the table gstTabBTable 
 */
void
shutdown_table_gstTabBTable(void)
{
    /*
     * call interface shutdown code
     */
    _gstTabBTable_shutdown_interface(&gstTabBTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
gstTabBTable_rowreq_ctx_init(gstTabBTable_rowreq_ctx * rowreq_ctx,
                             void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:gstTabBTable:gstTabBTable_rowreq_ctx_init",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:210:o: |-> Perform extra gstTabBTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
}                               /* gstTabBTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void
gstTabBTable_rowreq_ctx_cleanup(gstTabBTable_rowreq_ctx * rowreq_ctx)
{
    DEBUGMSGTL(("verbose:gstTabBTable:gstTabBTable_rowreq_ctx_cleanup",
                "called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:211:o: |-> Perform extra gstTabBTable rowreq cleanup.
     */
}                               /* gstTabBTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
gstTabBTable_pre_request(gstTabBTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:gstTabBTable:gstTabBTable_pre_request",
                "called\n"));

    /*
     * TODO:510:o: Perform gstTabBTable pre-request actions.
     */

    return MFD_SUCCESS;
}                               /* gstTabBTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
gstTabBTable_post_request(gstTabBTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:gstTabBTable:gstTabBTable_post_request",
                "called\n"));

    /*
     * TODO:511:o: Perform gstTabBTable post-request actions.
     */

    return MFD_SUCCESS;
}                               /* gstTabBTable_post_request */


/** @{ */
