/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef GSTTABBTABLE_INTERFACE_H
#define GSTTABBTABLE_INTERFACE_H

#ifdef __cplusplus
extern          "C" {
#endif


#include "gstTabBTable.h"


    /*
     ********************************************************************
     * Table declarations
     */

    /*
     * PUBLIC interface initialization routine 
     */
    void           
        _gstTabBTable_initialize_interface(gstTabBTable_registration *
                                           user_ctx, u_long flags);
    void           
        _gstTabBTable_shutdown_interface(gstTabBTable_registration *
                                         user_ctx);

    gstTabBTable_registration *gstTabBTable_registration_get(void);

    gstTabBTable_registration
        *gstTabBTable_registration_set(gstTabBTable_registration * newreg);

    netsnmp_container *gstTabBTable_container_get(void);
    int             gstTabBTable_container_size(void);

    gstTabBTable_rowreq_ctx *gstTabBTable_allocate_rowreq_ctx(void *);
    void            gstTabBTable_release_rowreq_ctx(gstTabBTable_rowreq_ctx
                                                    * rowreq_ctx);

    int             gstTabBTable_index_to_oid(netsnmp_index * oid_idx,
                                              gstTabBTable_mib_index *
                                              mib_idx);
    int             gstTabBTable_index_from_oid(netsnmp_index * oid_idx,
                                                gstTabBTable_mib_index *
                                                mib_idx);

    /*
     * access to certain internals. use with caution!
     */
    void            gstTabBTable_valid_columns_set(netsnmp_column_info
                                                   *vc);


#ifdef __cplusplus
}
#endif
#endif                          /* GSTTABBTABLE_INTERFACE_H */
/** @} */
