/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-oids.m2c 12855 2005-09-27 15:56:08Z rstory $
 *
 * $Id:$
 */
#ifndef GSTTABATABLE_OIDS_H
#define GSTTABATABLE_OIDS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     * column number definitions for table gstTabATable 
     */
#define GSTTABATABLE_OID              1,3,6,1,3,1977,1,3

#define COLUMN_GSTTABAINDEX         1

#define COLUMN_GSTTABADATA         2


#define GSTTABATABLE_MIN_COL   COLUMN_GSTTABAINDEX
#define GSTTABATABLE_MAX_COL   COLUMN_GSTTABADATA



#ifdef __cplusplus
}
#endif
#endif                          /* GSTTABATABLE_OIDS_H */
