/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file gstTabBTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef GSTTABBTABLE_DATA_GET_H
#define GSTTABBTABLE_DATA_GET_H

#ifdef __cplusplus
extern          "C" {
#endif

    /*
     *********************************************************************
     * GET function declarations
     */

    /*
     *********************************************************************
     * GET Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table gstTabBTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * GUILE-SNMP-TEST-MIB::gstTabBTable is subid 4 of gstMibObjects.
     * Its status is Current.
     * OID: .1.3.6.1.3.1977.1.4, length: 8
     */
    /*
     * indexes
     */

    int             gstTabBData_get(gstTabBTable_rowreq_ctx * rowreq_ctx,
                                    char **gstTabBData_val_ptr_ptr,
                                    size_t *gstTabBData_val_ptr_len_ptr);


    int             gstTabBTable_indexes_set_tbl_idx(gstTabBTable_mib_index
                                                     * tbl_idx,
                                                     long gstTabBIndex_val,
                                                     char
                                                     *gstTabBIndex2_val_ptr,
                                                     size_t
                                                     gstTabBIndex2_val_ptr_len);
    int             gstTabBTable_indexes_set(gstTabBTable_rowreq_ctx *
                                             rowreq_ctx,
                                             long gstTabBIndex_val,
                                             char *gstTabBIndex2_val_ptr,
                                             size_t
                                             gstTabBIndex2_val_ptr_len);




#ifdef __cplusplus
}
#endif
#endif                          /* GSTTABBTABLE_DATA_GET_H */
/** @} */
