/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef GSTTABBTABLE_DATA_ACCESS_H
#define GSTTABBTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern          "C" {
#endif


    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table gstTabBTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * GUILE-SNMP-TEST-MIB::gstTabBTable is subid 4 of gstMibObjects.
     * Its status is Current.
     * OID: .1.3.6.1.3.1977.1.4, length: 8
     */


    int             gstTabBTable_init_data(gstTabBTable_registration *
                                           gstTabBTable_reg);


    /*
     * TODO:180:o: Review gstTabBTable cache timeout.
     * The number of seconds before the cache times out
     */
#define GSTTABBTABLE_CACHE_TIMEOUT   60

    void            gstTabBTable_container_init(netsnmp_container **
                                                container_ptr_ptr,
                                                netsnmp_cache * cache);
    void            gstTabBTable_container_shutdown(netsnmp_container *
                                                    container_ptr);

    int             gstTabBTable_container_load(netsnmp_container *
                                                container);
    void            gstTabBTable_container_free(netsnmp_container *
                                                container);

    int             gstTabBTable_cache_load(netsnmp_container * container);
    void            gstTabBTable_cache_free(netsnmp_container * container);

    /*
     ***************************************************
     ***             START EXAMPLE CODE              ***
     ***---------------------------------------------***/
    /*
     *********************************************************************
     * Since we have no idea how you really access your data, we'll go with
     * a worst case example: a flat text file.
     */
#define MAX_LINE_SIZE 256
    /*
     ***---------------------------------------------***
     ***              END  EXAMPLE CODE              ***
     ***************************************************/
    int             gstTabBTable_row_prep(gstTabBTable_rowreq_ctx *
                                          rowreq_ctx);



#ifdef __cplusplus
}
#endif
#endif                          /* GSTTABBTABLE_DATA_ACCESS_H */
